version: '3.8'

services:

  envoy-proxy:
    build: ./envoy_proxy
    ports:
    - "${PORT_PROXY:-10000}:10000/udp"
    - "${PORT_ADMIN:-10001}:10001"

  syslog-receiver:
    build: ./syslog_receiver
    ports:
      - "514:514/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  syslog-client:
    build: ./syslog_client
    environment:
      - SYSLOG_SERVER=syslog-receiver
    depends_on:
      - syslog-receiver
      - envoy-proxy
    deploy:
      replicas: 40
    restart: unless-stopped
