version: '3.8'

services:

  envoy-proxy:
    build: ./envoy_proxy
    ports:
    - "${PORT_PROXY:-10000}:10000/udp"
    - "${PORT_ADMIN:-10001}:10001"
    restart: unless-stopped

  syslog-server-1:
    build: ./syslog_server
    ports:
      - "514:514/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  syslog-server-2:
    build: ./syslog_server
    ports:
      - "515:515/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  syslog-client:
    build: ./syslog_client
    environment:
      - ENVOY_SERVER=envoy-proxy
      - ENVOY_PORT=10000
      - SLEEP_TIMEOUT=0
    depends_on:
      - syslog-server-1
      - syslog-server-2
      - envoy-proxy
    deploy:
      replicas: 5
    restart: unless-stopped
